version: "3"

services:
  nginx:
    image: nginx
    restart: ${RESTART}
    ports:
      - ${HTTP_PORT}:80
    working_dir: "/var/www"
    volumes:
      - "./backend:/var/www"
      - "./build/nginx/site.conf.template:/etc/nginx/templates/default.conf.template"
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
    depends_on:
      - backend


  backend:
    build:
      context: "."
      dockerfile: "./build/php/Dockerfile"
    working_dir: "/var/www"
    volumes:
      - "./backend:/var/www"
      - "./build/php/log-stdout.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
      - "./build/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./build/php/mail.ini:/usr/local/etc/php/conf.d/mail.ini"
      - "./build/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
      - "./build/mail/msmtprc.template:/etc/msmtprc.template"
      - "./build/bitrix/cron_events.sh:/usr/local/sbin/cron_events.sh"
      - "./build/bitrix/install_bitrix.sh:/usr/local/sbin/install_bitrix.sh"
      - "./build/php/start.sh:/usr/local/sbin/start.sh"
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - DISTR_URL=${DISTR_URL}
      - XDEBUG_CONFIG=remote_host=${HOST_IP}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
      - CRON_INTERVAL_SEC=${CRON_INTERVAL_SEC}
      - SMTP_USER=${SMTP_USER}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_HOSTNAME=${SMTP_HOSTNAME}
      - RECOMMEND_PRODUCT_ID=${RECOMMEND_PRODUCT_ID}
      - BOOK_BLOCK_ID=${BOOK_BLOCK_ID}
      - NON_BOOK_BLOCK_ID=${NON_BOOK_BLOCK_ID}
      - FOOD_BLOCK_ID=${FOOD_BLOCK_ID}
    command: ["/usr/local/sbin/start.sh"]
    depends_on:
      - database

  database:
    image: mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
    volumes:
      - "./database/data:/var/lib/mysql"
      - "./database:/docker-entrypoint-initdb.d"
    security_opt:
      - seccomp:unconfined